from typing import List, Dict, Any
from pydantic import BaseModel, Field

class RawChunk(BaseModel):
    """The raw chunk after scraping, cleaning, and chunking"""
    id: str
    doc_id: str = Field(..., description="Unique hash/ID of the parent scraped document/URL")
    source_url: str
    title: str
    content: str
    tags: List[str]

class GeneratedQuestion(BaseModel):
    """Question generated by the LLM from a chunk"""
    id: str
    chunk_id: str
    content: str
    tags: List[str]

class GeneratedQuestionSet(BaseModel):
    """The strict schema enforced on the LLM output."""
    questions: List[str] = Field(description="3 to 5 realistic questions that this text chunk answers directly.")