from typing import List, Optional
from pydantic import BaseModel, Field

class RetrievedContextItem(BaseModel):
    """A retrieved chunk/document passed as grounding context."""
    title: str = Field(default="", description="Source document or page title")
    content: str = Field(..., description="The relevant passage text")
    source_url: Optional[str] = Field(default=None, description="URL or reference link")

class QARequest(BaseModel):
    """The incoming user query along with retrieved passages."""
    query: str = Field(..., description="The user's original or expanded query")
    contexts: List[RetrievedContextItem] = Field(
        default_factory=list, 
        description="Ranked chunks retrieved from vector search"
    )

class QAResponse(BaseModel):
    """Synthesized final response from the RAG pipeline."""
    answer: str = Field(..., description="Ground-truth answer generated by the model")
    sources: List[str] = Field(
        default_factory=list, 
        description="Unique source URLs or references used to synthesize the answer"
    )